name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - Angel's-branch
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - Angel's-branch

permissions:
  contents: write

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      # Fix permissions and clean Git configuration
      - name: Fix Git configuration permissions
        run: |
          sudo chown -R $(whoami) .git/
          sudo chmod -R u+rw .git/
          git config --global --unset-all http.https://github.com/.extraheader || true
          git config --local --unset-all http.https://github.com/.extraheader || true

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build

      - name: Check output directory
        run: |
          echo "Listing directories in the current folder:"
          ls -la
          echo "Checking for common build output directories:"
          if [ -d "build" ]; then echo "build directory exists"; fi
          if [ -d "dist" ]; then echo "dist directory exists"; fi
          if [ -d "public" ]; then echo "public directory exists"; fi
          if [ -d "_site" ]; then echo "site directory exists"; fi
          if [ -d "out" ]; then echo "out directory exists"; fi

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ZEALOUS_TREE_05AFCCC10 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          ###### Repository/Build Configurations ######
          app_location: "/" # App source code path
          api_location: "api" # API source code path
          output_location: "" # Set this to the actual output directory from your build, leave blank if the app_location already contains the built files
          ###### End of Repository/Build Configurations ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ZEALOUS_TREE_05AFCCC10 }}
          action: "close"
