name: Build and deploy Node.js app to Azure Web App - naturekingdomBE

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Cache Node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('server/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: |
          cd server
          npm ci

      - name: Run tests (if applicable)
        run: |
          cd server
          npm test || true

      - name: Create deployment package
        run: |
          cd server
          # Make sure package-lock.json is included in the ZIP
          zip -r ../release.zip . -x "node_modules/*" ".git*"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: |
          mkdir -p server-deploy
          unzip release.zip -d server-deploy
          ls -la server-deploy

      - name: Install production dependencies
        run: |
          cd server-deploy
          # Check if package-lock.json exists
          if [ -f "package-lock.json" ]; then
            echo "Found package-lock.json, running npm ci"
            npm ci --omit=dev
          else
            echo "No package-lock.json found, using npm install instead"
            npm install --omit=dev
          fi

      - name: Setup Environment Variables
        run: |
          echo "NODE_ENV=production" >> $GITHUB_ENV

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_1B4AE99ADEE44A9D9EF339FBACE118DF }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_6D9B96F60759422C9AC522B18653A441 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_9845D10D63E3497A8FF956C1CEDB6E34 }}

      - name: "Deploy to Azure Web App"
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: "naturekingdomBE"
          slot-name: "Production"
          package: server-deploy

      - name: "Post-deployment verification"
        run: |
          echo "Deployed successfully to ${{ steps.deploy-to-webapp.outputs.webapp-url }}"
          sleep 30 # Give the app time to start
          curl -sSf "${{ steps.deploy-to-webapp.outputs.webapp-url }}" || echo "Website might still be starting up"
