# Improved workflow for deploying Node.js backend to Azure Web App
name: Build and deploy Node.js app to Azure Web App - naturekingdomBE

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: "18.x" # Changed to 18.x as it's more stable than 22.x

      - name: Install dependencies
        run: npm ci # Use 'npm ci' for clean installs in CI environments

      - name: Run tests (if applicable)
        run: npm test || true # Add this if you have tests, '|| true' makes it non-blocking

      - name: Create deployment package
        run: zip -r release.zip . -x "node_modules/*" ".git*" # Exclude node_modules and git files

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Install production dependencies
        run: npm ci --production # Install only production dependencies

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_1B4AE99ADEE44A9D9EF339FBACE118DF }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_6D9B96F60759422C9AC522B18653A441 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_9845D10D63E3497A8FF956C1CEDB6E34 }}

      - name: "Deploy to Azure Web App"
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: "naturekingdomBE"
          slot-name: "Production"
          package: .

      - name: "Post-deployment verification"
        run: |
          echo "Deployed successfully to ${{ steps.deploy-to-webapp.outputs.webapp-url }}"
          curl -sSf "${{ steps.deploy-to-webapp.outputs.webapp-url }}" || echo "Website might still be starting up"
